tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                /* Surfaces */
                "background":                 "#faf9f7",
                "surface":                    "#faf9f7",
                "surface-bright":             "#faf9f7",
                "surface-dim":                "#dadad8",
                "surface-variant":            "#e3e2e0",
                "surface-container-lowest":   "#ffffff",
                "surface-container-low":      "#f4f3f1",
                "surface-container":          "#efeeec",
                "surface-container-high":     "#e9e8e6",
                "surface-container-highest":  "#e3e2e0",
                /* On-surfaces */
                "on-background":              "#1a1c1b",
                "on-surface":                 "#1a1c1b",
                "on-surface-variant":         "#4b463f",
                "inverse-surface":            "#2f3130",
                "inverse-on-surface":         "#f1f1ef",
                /* Primary */
                "primary":                    "#181612",
                "on-primary":                 "#ffffff",
                "primary-container":          "#2d2a26",
                "on-primary-container":       "#96918b",
                "primary-fixed":              "#e8e1db",
                "primary-fixed-dim":          "#ccc5bf",
                "on-primary-fixed":           "#1e1b17",
                "on-primary-fixed-variant":   "#4a4642",
                "inverse-primary":            "#ccc5bf",
                /* Secondary — coral accent */
                "secondary":                  "#a13e2b",
                "on-secondary":               "#ffffff",
                "secondary-container":        "#fc836a",
                "on-secondary-container":     "#721c0c",
                "secondary-fixed":            "#ffdad3",
                "secondary-fixed-dim":        "#ffb4a5",
                "on-secondary-fixed":         "#3e0400",
                "on-secondary-fixed-variant": "#812716",
                /* Tertiary */
                "tertiary":                   "#161613",
                "on-tertiary":                "#ffffff",
                "tertiary-container":         "#2b2a27",
                "on-tertiary-container":      "#93918d",
                "tertiary-fixed":             "#e6e2dd",
                "tertiary-fixed-dim":         "#c9c6c1",
                "on-tertiary-fixed":          "#1c1c19",
                "on-tertiary-fixed-variant":  "#484743",
                /* Outline */
                "outline":                    "#7c766e",
                "outline-variant":            "#cdc5bc",
                /* Error */
                "error":                      "#ba1a1a",
                "on-error":                   "#ffffff",
                "error-container":            "#ffdad6",
                "on-error-container":         "#93000a",
                /* Misc */
                "surface-tint":               "#625e59",
            },
            borderRadius: {
                DEFAULT: "1rem",
                lg:      "2rem",
                xl:      "3rem",
                full:    "9999px",
            },
            spacing: {
                "margin-desktop": "48px",
                "margin-mobile":  "20px",
                "gutter":         "16px",
                "container-max":  "1440px",
                "unit":           "8px",
            },
            fontFamily: {
                "display-xl":         ["Libre Caslon Text", "Georgia", "serif"],
                "display-lg":         ["Libre Caslon Text", "Georgia", "serif"],
                "display-md":         ["Libre Caslon Text", "Georgia", "serif"],
                "headline-lg":        ["Libre Caslon Text", "Georgia", "serif"],
                "headline-lg-mobile": ["Libre Caslon Text", "Georgia", "serif"],
                "headline-md":        ["Libre Caslon Text", "Georgia", "serif"],
                "body-lg":            ["DM Sans", "system-ui", "sans-serif"],
                "body-md":            ["DM Sans", "system-ui", "sans-serif"],
                "label-md":           ["DM Sans", "system-ui", "sans-serif"],
                "label-sm":           ["DM Sans", "system-ui", "sans-serif"],
            },
            fontSize: {
                "display-xl":         ["72px", { lineHeight: "1.0", letterSpacing: "-0.03em", fontWeight: "400" }],
                "display-lg":         ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
                "display-md":         ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
                "headline-lg":        ["40px", { lineHeight: "1.2", fontWeight: "400" }],
                "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
                "headline-md":        ["24px", { lineHeight: "1.3", fontWeight: "400" }],
                "body-lg":            ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-md":            ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md":           ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
                "label-sm":           ["12px", { lineHeight: "1.4", letterSpacing: "0.08em", fontWeight: "700" }],
                "label-xs":           ["10px", { lineHeight: "1.3", letterSpacing: "0.10em", fontWeight: "700" }],
            },
        },
    },
};
